[rust]
toolchain = "1.89.0"
edition = "2024"
profile = "release"

[test]
auto_before_submit = true
default_tle_sec = 2

[download]
timeout_sec = 30

[atcoder]
url = "https://atcoder.jp/"
language_id = "5054"
language_name = "Rust (rustc 1.89.0)"

[codeforces]
url = "https://codeforces.com/"
language_id = "75"
language_name = "Rust 2024"

[yukicoder]
url = "https://yukicoder.me/"
language_id = "rust"
language_name = "Rust"
